# Generated by Django 4.2.2 on 2023-06-25 13:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('guid', models.CharField(db_column='guid', default=uuid.uuid4, editable=False, max_length=64, primary_key=True, serialize=False, verbose_name='key')),
                ('amount', models.FloatField(default=0.0, verbose_name='amount')),
                ('reason', models.CharField(choices=[('rec', 'receipt'), ('wri', 'write-downs')], default='rec', max_length=10)),
                ('on_delete', models.BooleanField(db_index=True, default=False, verbose_name='Deleted')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date of update')),
            ],
        ),
    ]
